# Generated by Django 3.2.8 on 2021-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=950)),
                ('devise', models.CharField(choices=[('Eur', 'Eur'), ('Dollar', 'Dollar'), ('Sol', 'Sol')], default='Eur', max_length=20)),
                ('zone', models.CharField(choices=[('Europe', 'Europe'), ('Asie', 'Asie'), ('Amerique', 'Amerique')], default='0', max_length=100)),
                ('borower', models.CharField(default='0', max_length=100)),
                ('lender', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(choices=[('Closing', 'Closing'), ('Structuring', 'Structuring'), ('Push', 'Push')], default='Waiting', max_length=20)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
